### ISSUE TITLE
Issues with unrecognized parameter "cartId"

### ISSUE THREAD

**Issue by tqvarnst** [jbossdemocentral/coolstore-microservice#116]
When the coolstore-gw is parsing the response from the cart service it includes parameter "cartId", which is not recognized by the coolstore-gw.

**Comment by mikecroft** [comment]
This problem is also on the `stable-ocp-3.9`  and `-3.10` branches. I made PR #113 to fix it in `3.9`, but it might be better to backport this change instead. WDYT @tqvarnst?
