### ISSUE TITLE
coolstore-gw are not using MAVEN_MIRROR_URL 

### ISSUE THREAD

**Issue by tqvarnst** [jbossdemocentral/coolstore-microservice#13]
The fis-java-openshift:2.0 image is not capable of using MAVEN_MIRROR_URL. The solution is to add a custom setting.xml. We are in discussion with engineering to add support MAVEN_MIRROR_URL.

**Comment by jcordes73** [comment]
@tqvarnst Any upfdates on this? Seems this is still not available on fis-java-openshift:2.0 image ...

**Comment by tqvarnst** [comment]
IIRC correctly @siamaksade had spoken to Keith about this and it should fixed next version.

**Comment by siamaksade** [comment]
Fixed with 181273164ca9c58caee3cd1bb89ccd55dbe5e426
