### ISSUE TITLE
api-gateway process is needing SSO_URL param

### ISSUE THREAD

**Issue by jarcher** [jbossdemocentral/coolstore-microservice#16]
running the oc process -f api-gateway.json | oc create -f -

error: error processing the template "api-gateway": Template "api-gateway" is invalid: template.parameters[1]: Required value: template.parameters[1]: parameter SSO_URL is required and must be specified
error: no objects passed to create

I see the https://secure-sso-<project>.<default-domain-suffix> in the api-gateway.json and updated it according to my server instance but it is still throwing the error

**Comment by jamesfalkner** [comment]
You must specify the value of SSO_URL (and SSO_PUBLIC_KEY) on the command line, as per the [ver1.0 docs](https://github.com/jbossdemocentral/coolstore-microservice/blob/ver1.0/README.md). So something like:

```
oc process -f api-gateway.json \
    SSO_URL=https://secure-sso-${OCP_PROJECT}.${OCP_DOMAIN}/auth \
    SSO_PUBLIC_KEY=${PUBLIC_KEY} | \
    oc create -f -
```

**Comment by tqvarnst** [comment]
I'm going to close this because of inactivity. Also since SSO implementation has been replaced I don't believe that this is an issue anymore.
