### ISSUE TITLE
Project needs to be created and template needs to be processed as "developer" user

### ISSUE THREAD

**Issue by DuncanDoyle** [jbossdemocentral/coolstore-microservice#22]
If you follow the installation documentation, the "coolstore" project is created under the "system:admin" user. The template is also processed as this user. You can't login with this user in the OpenShift console, which makes it impossible to see the project in the console.

We need to specify that you need to change user to "developer" before creating the project,

**Comment by jamesfalkner** [comment]
I use the [oc-cluster-wrapper](http://github.com/openshift-evangelists/oc-cluster-wrapper) and it sets up the 'admin' user as a cluster-admin via

```
oc adm policy add-cluster-role-to-user cluster-admin admin --as=system:admin
```

This is a workaround only though. Should fix the docs.
