### ISSUE TITLE
Clearing shopping cart results in $2.99 shipping charge remaining

### ISSUE THREAD

**Issue by jamesfalkner** [jbossdemocentral/coolstore-microservice#32]
Adding and then removing all items in the shopping cart results in a persistent $2.99 shipping charge.

![299](https://cloud.githubusercontent.com/assets/861894/22268793/ce483718-e256-11e6-9369-a5ffcd5130a5.gif)

**Comment by jamesfalkner** [comment]
@DuncanDoyle can you take a look?

**Comment by DuncanDoyle** [comment]
RuleFlow now has an X-OR Gateway which checks (using Drools constraints) whether there are items in the shopping cart. When there are no items, we don't fire any rules (i.e. we don't activate any ruleflow groups) and thus the pricing stays 0.

![com redhat coolstore priceprocess](https://cloud.githubusercontent.com/assets/875822/22378150/e93f582a-e4b4-11e6-844b-13117a505d8a.png)

**Comment by DuncanDoyle** [comment]
Can we close this?
