### ISSUE TITLE
Quota limits reach in OpenShift online

### ISSUE THREAD

**Issue by weimeilin79** [jbossdemocentral/coolstore-microservice#37]
Due to the quota limit of resource on OpenShift Online, running this demo can be difficult. 
Please state it somewhere in the doc, adding the CPU/RAM requirement for running this demo.

**Comment by siamaksade** [comment]
Mem and cpu requirements added to the provisioning docs:
https://github.com/jbossdemocentral/coolstore-microservice/tree/stable-ocp-3.4/openshift/scripts

OpenShift Online Dev Preview currently allows 2GB mem which is not enough.
