### ISSUE TITLE
Replace Cart service EAP with Spring

### ISSUE THREAD

**Issue by siamaksade** [jbossdemocentral/coolstore-microservice#47]
It's already done in the stable branches (38b31802c4404a1d3dc34f9a19d3fe74634bb746 and fee7d078281470ecfffba1492640f9eea65dabf8) but needs to be done in master with moving the decision server code to the Spring repo

**Comment by siamaksade** [comment]
@jamesfalkner @tqvarnst

**Comment by DuncanDoyle** [comment]
@siamaksade "with moving the decision server code to the Spring repo" .... What do you mean with that sentence?

I've just done quite some work on the Cart service (the SpringBoot one) on master, so AFAICT, we can close this issue once PR #62 gets merged ....

**Comment by siamaksade** [comment]
Agree, we can close this. Before we had a cart-eap and cart-spring service which this issues refers to. We have only Spring now.
