### ISSUE TITLE
Missing Fis ImageStream

### ISSUE THREAD

**Issue by alekonkoisp** [jbossdemocentral/coolstore-microservice#59]
Using new minishift cluster,  Coolstore-gw doesn't compile for missing fuse image stream.

Fixed with 
oc create -f https://raw.githubusercontent.com/jboss-fuse/application-templates/master/fis-image-streams.json -n openshift

is it correct?

bye
Ale

**Comment by DuncanDoyle** [comment]
I think this is correct (at least that's how I do it as well). There is another issue with somewhat the same question, so I'll close this. Duplicate of #58
