### ISSUE TITLE
provision_demo.sh doesn't populate gogs repo

### ISSUE THREAD

**Issue by thom-at-redhat** [jbossdemocentral/coolstore-microservice#77]
provision_demo.sh has an issue where it tries to extract a zip file using tar.  This causes an issue where the gogs repo is not populated.

There is a workaround involving unzip and moving the files around to mimic "--strip 1"

**Comment by trepel** [comment]
This has been already fixed in 1.1.x, see
https://github.com/jbossdemocentral/coolstore-microservice/commit/7b91e07f5937e3113b6f97f62b48a82b5d82193b
