### ISSUE TITLE
Add a NoSQL backend service

### ISSUE THREAD

**Issue by cmoulliard** [jbossdemocentral/coolstore-microservice#8]
The catalog service create a list of Product object when the class is instantiated

https://github.com/cmoulliard/coolstore-microservice/blob/master/catalog-service/src/main/java/com/redhat/coolstore/service/CatalogService.java

It could be interesting to have within the same pod, another microservice deployed to expose a NoSQL database/storage (Redis, ....)

**Comment by akram** [comment]
@cmoulliard Hi Charles
here is something that I've done.
It is lacking the integration of the mongodb template
https://github.com/akram/coolstore-microservice/commits/mongodb_integration

**Comment by tqvarnst** [comment]
In branch demo-1 we have change the catalog service to use MongoDB for storage. This will be added to the master branch shortly.
