### ISSUE TITLE
Integrate CartService as BRMS service

### ISSUE THREAD

**Issue by akram** [jbossdemocentral/coolstore-microservice#9]
Based on the brms-coolstore, it could be nice if we could integrate the CartService as a BRMS backed service.

**Comment by jamesfalkner** [comment]
The work done by @DuncanDoyle in https://github.com/jbossdemocentral/brms-coolstore-demo/issues/64 should make this much easier

**Comment by DuncanDoyle** [comment]
Assigned myself. Working on this as we speak. The idea is to add the BRMS Coolstore Repo in a DecisionServer63 S2I build and use the KIE Server Client to communicate from the "cart-service" to the rules service. I've got all the pieces in place, just need to connect the dots. Expect a PR later this week.
