### ISSUE TITLE
coolstorage-gw deployment cannot find image

### ISSUE THREAD

**Issue by isnuryusuf** [jbossdemocentral/coolstore-microservice#99]
An error occurred while starting the build.Error resolving ImageStreamTag fis-java-openshift:2.0 in namespace openshift: unable to find latest tagged image

**Comment by siamaksade** [comment]
You are missing some imagestreams as stated in the troubleshooting section:
https://github.com/jbossdemocentral/coolstore-microservice#troubleshooting

**Comment by altuga** [comment]
Hello 

I installed all imagestreams at [https://github.com/jbossdemocentral/coolstore-microservice/tree/stable-ocp-3.11) but still, coolserver-gw service cannot be built. ](https://github.com/jbossdemocentral/coolstore-microservice/tree/stable-ocp-3.11) but still, coolserver-gw service cannot be built. 

Error messsage : An error occurred while starting the build.
 Reason: Error resolving ImageStreamTag fis-java-openshift:2.0 in namespace openshift: unable to find latest tagged image

Any suggestions ?
Thanks
